version: '3.9'

services:
    clicker-vue:
        container_name: clicker-vue
        restart: always
        ports:
            - 8080:8080
        hostname: clicker-vue
        build:
            dockerfile: Dockerfile
            context: .
            target: development
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            API_URL: https://clicker-vue.ru/api/
            VITE_USE_MOCKS: true
    # proxy:
    #     build:
    #         context: .docker/proxy
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - clicker-vue
    #     ports:
    #         - 8082:80
    #     volumes:
    #         - .docker/proxy/templates:/etc/nginx/templates
